import path from 'path';
import imageminGifsicle from 'imagemin-gifsicle';
import imageminMozjpeg from 'imagemin-mozjpeg';
import imageminPngquant from 'imagemin-pngquant';
import imageminSvgo from 'imagemin-svgo';

function setImageSize(options) {
    const imageSize = {
        '0': [800, 800],
        '1': [1280, 1280],
        '2': [1600, 1600],
        '3': [2048, 2048]
    }
    return imageSize[options.resolution]
}

function setOutputType(options, file) {
    switch(options.outputType) {
        case '0':
            return path.format({
                        dir: path.dirname(file),
                        base: path.basename(file, path.extname(file)) + options.outputFilename + path.extname(file)
                    });
        case '1':
            return path.format({
                        dir: path.join(path.dirname(file), options.outputNewFolder),
                        base: path.basename(file)
                    });
        case '2':
            return path.format({
                        dir: options.outputPath,
                        base: path.basename(file)
                    });
    }
}

const imageMinPlugins = [
    imageminMozjpeg({ quality: 80 }),
    imageminPngquant({ quality: [0.6, 0.8] }),
    imageminGifsicle({ optimizationLevel: 2 }),
    imageminSvgo({
        plugins: [
            {
                removeTitle: true,
                removeDimensions: true,
            },
        ],
    }),
];

const HTMLMinifySettings = {
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: true,
    collapseWhitespace: true,
    includeAutoGeneratedTags: false,
    minifyCSS: true,
    minifyJS: true,
    minifyURLs: true,
    quoteCharacter: "'",
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeEmptyElements: true,
    removeOptionalTags: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    removeTagWhitespace: true,
};

const CleanCSSSettings = {
    level: 2
}

export { setImageSize, setOutputType, imageMinPlugins, HTMLMinifySettings, CleanCSSSettings }